### PR TITLE
allow users to set a custom sender email, defaulting to the admin email

### PR DESCRIPTION
**Pull request by ChemiKyle**
Addresses issue #12 with discussed functionality

### CODE REVIEW

**Comment by marlycormar** [comment]
Hi @ChemiKyle, I added some small corrections to the readme in a PR#2 against your repo.

**Comment by marlycormar** [comment]
The desired effect when clicking **Use Custom Email Sender** seems to be inverted. If the checkbox **Use Custom Email Sender** is clicked and an email is set, the user with get an email from the 'project_contact_email'. If **Use Custom Email Sender** is not clicked, the user will not receive any email.

_Note_: tested this PR in stage_b. The module is currently deployed as v0.0.0 and the cron job is set to run every minute. There is a local git repo associated with this folder in case any change needs to be reverted.

**Comment by ChemiKyle** [comment]
@marlycormar I think the "Set a universal 'FROM' email address for *all* emails sent from REDCap (optional)" field may be the culprit. It is set in stage_b but not in my VM.

Screen Shot 2019-09-19 at 8 52 47 AM

**Comment by marlycormar** [comment]
Tested the module with a universal email address set up and without.

**Pull request merged**
